### ISSUE TITLE
GCloud and Dataverse Integration

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#13]
Need ability to do the following things from Python
- [x] Read CSV files from GCS into Pandas
- [x] Save CSV files from Python (perhaps even Pandas directly) to GCS and BQuery
- [x] Authenticate with Google both on CircleCI builds and Colab environments.
- [ ] Code to load CSV Dataverse to model

**Comment by isaacmg** [comment]
@aradhanacha  Would you want to look into the last two items related to this? Basically if the config is supplied a gs:// path it should download it and load it to a directory then use that file. Similarily if it is supplied a data verse url it should download it and load it

**Comment by aradhanacha** [comment]
@isaacmg Sure I can check that..

**Comment by isaacmg** [comment]
I'm going to remove the BQ stuff this as that has a separate issue #102

**Comment by isaacmg** [comment]
I'll test this end to end in a notebook today then close if it works.
