### ISSUE TITLE
Add link to documentation in the README

### ISSUE THREAD

**Issue by rjurney** [AIStream-Peelout/flow-forecast#142]
I can’t find a homepage or link to the documentation for the project but given the activity it seems unlikely it doesn’t exist anywhere as I see a docs folder. Where is the documentation so I can read about what the project does?

**Comment by isaacmg** [comment]
[ReadTheDocs](https://flow-forecast.readthedocs.io/en/latest/). The [Wiki pages](https://github.com/AIStream-Peelout/flow-forecast/wiki/Training-models) are the best how to actually use the repo though.  Whereas ReadTheDocs is probably the best for detailed documentation.

**Comment by rjurney** [comment]
Thanks, it was there I just kept looking over it. Human error.
