### ISSUE TITLE
TypeError: Object of type Tensor is not JSON serializable when running train_transformer_style with takes_target as 1

### ISSUE THREAD

**Issue by 97harsh** [AIStream-Peelout/flow-forecast#197]
> Traceback (most recent call last):
>   File "flood_forecast/trainer.py", line 108, in <module>
>     main()
>   File "flood_forecast/trainer.py", line 103, in main
>     train_function(training_config["model_type"], training_config)
>   File "flood_forecast/trainer.py", line 42, in train_function
>     train_transformer_style(model=trained_model,
>   File "/home/harsh/Documents/Coronawhy/flow-forecast/flood_forecast/pytorch_training.py", line 146, in train_transformer_style
>     model.save_model(model_filepath, max_epochs)
>   File "/home/harsh/Documents/Coronawhy/flow-forecast/flood_forecast/time_model.py", line 152, in save_model
>     json.dump(self.params, p)
>   File "/home/harsh/anaconda3/envs/flow-forecast/lib/python3.8/json/__init__.py", line 179, in dump
>     for chunk in iterable:
>   File "/home/harsh/anaconda3/envs/flow-forecast/lib/python3.8/json/encoder.py", line 431, in _iterencode
>     yield from _iterencode_dict(o, _current_indent_level)
>   File "/home/harsh/anaconda3/envs/flow-forecast/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/home/harsh/anaconda3/envs/flow-forecast/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/home/harsh/anaconda3/envs/flow-forecast/lib/python3.8/json/encoder.py", line 438, in _iterencode
>     o = _default(o)
>   File "/home/harsh/anaconda3/envs/flow-forecast/lib/python3.8/json/encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type Tensor is not JSON serializable

**Comment by 97harsh** [comment]
https://github.com/AIStream-Peelout/flow-forecast/blob/7927c5167c44fec0d0e4560de8d25e951d4eaa1e/flood_forecast/pytorch_training.py#L211-L212
this is updating the forward params with Tensor objects in models.params when takes_target==1
This should be sent as copy of dictionary instead of dictionary itself
https://github.com/AIStream-Peelout/flow-forecast/blob/7927c5167c44fec0d0e4560de8d25e951d4eaa1e/flood_forecast/pytorch_training.py#L90-L98

**Comment by 97harsh** [comment]
@isaacmg create a PR to should I change this ?

**Comment by isaacmg** [comment]
This didn't seem to occur before with the full transformer though https://github.com/AIStream-Peelout/flow-forecast/blob/7927c5167c44fec0d0e4560de8d25e951d4eaa1e/tests/full_transformer.json#L54

**Comment by isaacmg** [comment]
If that is the sole issue one would think this test should fail too https://github.com/AIStream-Peelout/flow-forecast/blob/7927c5167c44fec0d0e4560de8d25e951d4eaa1e/.circleci/config.yml#L251

**Comment by 97harsh** [comment]
The value t only gets tensor object when takes_target argument is passed to torch_single_train
