### ISSUE TITLE
No Provision of sending takes_target to call train_transformer_style in trainer.py

### ISSUE THREAD

**Issue by 97harsh** [AIStream-Peelout/flow-forecast#198]
No Provision of sending takes_target from config file in trainer.py, also ordering is incorrect
`        train_transformer_style(model=trained_model,
                                    training_params=params["training_params"],
                                takes_target=takes_target,
                                forward_params=params["forward_params"])`

https://github.com/AIStream-Peelout/flow-forecast/blob/7927c5167c44fec0d0e4560de8d25e951d4eaa1e/flood_forecast/trainer.py#L39

https://github.com/AIStream-Peelout/flow-forecast/blob/7927c5167c44fec0d0e4560de8d25e951d4eaa1e/flood_forecast/pytorch_training.py#L16-L21

**Comment by 97harsh** [comment]
@isaacmg can you take a look at this as well, I have to put in takes_target in config file, but there is no method currently parsing this info from
Dunno, why the testing failed

**Comment by isaacmg** [comment]
This has now been fixed see the merged PR
