### ISSUE TITLE
Anomaly detection

### ISSUE THREAD

**Issue by geoHeil** [AIStream-Peelout/flow-forecast#209]
Many thanks for the great work!

I would be interested in an example of anomaly detection. Do you have something similar or plan to add a tutorial about this topic?

**Comment by isaacmg** [comment]
Hey we currently don't support anomaly detection models at this point. We only have forecasting models. In the future we plan to add both classification and anomaly detection support.

**Comment by geoHeil** [comment]
Great! Already looking forward to it. 

FYI: perhaps https://github.com/jdb78/pytorch-forecasting is also useful for your forecasting endeavors.
