### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Vipermdl** [AIStream-Peelout/flow-forecast#240]
So how can i download the dataset of FlowDB Dataset? Gsutil is not working? Can you give some details for your dataset, and tell us how to use you model for gour FlowDB? Thanks!

**Comment by isaacmg** [comment]
You can download the dataset at https://console.cloud.google.com/storage/browser/aistream-datasets. For instance a file URL is `https://storage.googleapis.com/aistream-datasets/day_addition/01037380KRKD_flow.csv` For an example of how to run forecasting models look at this notebook below https://colab.research.google.com/drive/1vl6tgH78bNb9A5JP6NcfFHB189TIjy5c?usp=sharing (though you will have to change file paths to new bucket).

**Comment by Vipermdl** [comment]
Thanks for your reply! when I download dataset, I found another question.
![image](https://user-images.githubusercontent.com/32351961/105150752-1d260e80-5b40-11eb-8172-300dc1c59d65.png)

**Comment by Vipermdl** [comment]
Thank you very much! I'm appreciated for that. But I found another question about gsutil.
![image](https://user-images.githubusercontent.com/32351961/105152900-beae5f80-5b42-11eb-8d1d-97652c0d7b92.png)
So can your share your data by Google Drive?

**Comment by isaacmg** [comment]
Hey we cannot put the data on Google Drive due to large file size. Gsutil is very easy to use to download the whole dataset. Even on colab you could just run `gsutil cp -r gs://aistream-datasets/day_addition` and it will download the whole dataset.

**Comment by isaacmg** [comment]
https://colab.research.google.com/drive/1m2DjlzSh9D7ObQpPqwWAA0fb9dk1mdz-?usp=sharing

**Comment by Vipermdl** [comment]
Thanks, I'm very appreciated it!

**Comment by isaacmg** [comment]
I'm closing this for now. Feel free to reopen if you have further comments.
