### ISSUE TITLE
Requirements are outdated and inconsistent

### ISSUE THREAD

**Issue by navidivan** [AIStream-Peelout/flow-forecast#271]
On colab, trying to
!pip install --force-reinstall --upgrade -r requirements.txt

it basically is downgrading most of the exisiting modules, and at the end gives the following error:
Installed /usr/local/lib/python3.6/dist-packages/flood_forecast-0.95.dev0-py3.6.egg
Processing dependencies for flood-forecast==0.95.dev0
error: torch 1.7.1 is installed but torch==1.5.1 is required by {'torchvision'}

**Comment by isaacmg** [comment]
You can now simply  run `pip install flood-forecast` we will be updating the tutorial notebooks shortly.
