### ISSUE TITLE
Pandas SettingWithCopyWarning

### ISSUE THREAD

**Issue by SylvainLan** [AIStream-Peelout/flow-forecast#276]
Hello,

First of all I'd like to thank the initiative, I'm working on time series data and been struggling for a while to run DL models on my data, this repo is exactly what I needed.

I wanted to give a small contribution as I've begun to go through the code.

There are multiple times where copies pd.DataFrame instances are changed which raise Warnings, it's no big deal but I think there are more efficient ways to change these DataFrames.

If that sounds good, I can try a PR

**Comment by isaacmg** [comment]
Thanks for the issue and the PR. Now that is merged I'll close.
