### ISSUE TITLE
Training and evaluating models without weights-and-biases integration

### ISSUE THREAD

**Issue by andresC98** [AIStream-Peelout/flow-forecast#285]
I have been reading the documentation and exploring the existing tutorials, but none of them seem to show how to actually use flow-forecast without the w&b integration, to keep things as simple as possible. Is there a way to do it?

**Comment by isaacmg** [comment]
Hi you can choose to simply not specify a Wandb API key when prompted.

**Comment by andresC98** [comment]
Got it! Thanks!
