### ISSUE TITLE
Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same in Google Colab

### ISSUE THREAD

**Issue by NicolasMICAUX** [AIStream-Peelout/flow-forecast#303]
Using modified version from [Forecasting-Tutorial.ipynb](https://colab.research.google.com/drive/1u2xHJI_z-XoLTeFYGRzYS5PjdZGRakyG?usp=sharing), with GPU, I get error while training : 
`
RuntimeError('Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same')
`
I'm trying to run "Informer" model.

I do want to use CUDA if it's faster, but I don't know what i've done wrong here.

[Here](https://colab.research.google.com/drive/14dYmhBewtzol2oIou_lIiVRsoGEFmSEx?usp=sharing) is my code (commentator rights).
Any idea about this error ?
Thx
N. M.

**Comment by isaacmg** [comment]
Support for the Informer model is still experimental and incomplete. The currently merged PRs allow training and validation of the informer but do not allow inference on test data nor work out all the bugs associated with training on a GPU. The PR in progress aims #299 to address some of these issues and also validate results are the same as the original paper.

**Comment by NicolasMICAUX** [comment]
ok, thx you a lot !
