### ISSUE TITLE
Possibility to specify a 'grouping id' and 'date' col for series

### ISSUE THREAD

**Issue by andresC98** [AIStream-Peelout/flow-forecast#307]
Hi, first of all, congratulations on the brilliant work done for this library!

I am currently trying to get to work this library (particularly the transformer_bottleneck (logsparse) architecture) with the famous benchmark datasets 'Electricity' and 'Traffic'. However, both of these datasets have categorical ids which indicates different stations / lanes, respectively, time series. 

After reading the (a bit sparse) documentation, and checking some of the available examples, I couldn't figure out some of my main questions: 

- Is there an option in the configuration files for specifying a "grouping id" so that this behavior of the dataset is taken into account? (e.g. for taking into account individually each series according to its ids, for group scaling, ...)

- Apart from the "relevant_cols" and "target_col" attributes specification, is there a specific attribute in the config file for specifying the name of the date column?

Thanks in advance!

**Comment by isaacmg** [comment]
So currently these features are not supported. We hope to have support for these features in the next release 4/15.

**Comment by isaacmg** [comment]
So this has finally been solved with the CSVSeriesIDLoader though support is still experimental.

**Comment by isaacmg** [comment]
I will open separate issues regarding continuing problems.
