### ISSUE TITLE
DecoderTransformer: Distinguishing Know inputs from Observed inputs

### ISSUE THREAD

**Issue by Vergangenheit** [AIStream-Peelout/flow-forecast#347]
Hello Isaac. First of all thank you for this brilliant project.
I was able to run the Decoder Transformer on the EU Wind Energy dataset.

One question though. The model's paper, when defining the problem, says that some exogenous time series are known until the forecast horizon.
For example, I would like to add the wind forecast as a feature with a middle dimension equals to "forecast_length" and with the same time idx as the target.
Is there a way to model this in your config_file or at a lower level within the Loader objects?

Thank you

Lorenzo Ostano

**Comment by isaacmg** [comment]
Well generally unknown time series can be added as an additional target, whereas known time series can just be left as relevant columns. The first n_columns in relevant_cols will correspond to the number of targets (unknowns). https://flow-forecast.atlassian.net/wiki/spaces/FF/pages/364019713/Training+Models

**Comment by Vergangenheit** [comment]
Let's suppose I'm trying to forecast the "Austria" time series.
You mean something like below?

"target_col": ['Austria', 'Belgium', 'Bulgaria', 'Switzerland', 'Czechia',
                            'Germany', 'Denmark', 'Estonia', 'Spain', 'Finland', 'France', 'Greece',
                            'Croatia', 'Hungary', 'Ireland', 'Italy', 'Lithuania', 'Luxembourg',
                            'Latvia', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania',
                            'Slovenia', 'Slovakia', 'Sweden', 'United Kingdom'],
          "relevant_cols": ['Austria','Belgium', 'Bulgaria', 'Switzerland', 'Czechia',
                            'Germany', 'Denmark', 'Estonia', 'Spain', 'Finland', 'France', 'Greece',
                            'Croatia', 'Hungary', 'Ireland', 'Italy', 'Lithuania', 'Luxembourg',
                            'Latvia', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania',
                            'Slovenia', 'Slovakia', 'Sweden', 'United Kingdom', 'month', 'weekday']

**Comment by isaacmg** [comment]
No. In `relevant_cols` add all the feature time series. But start with the target ones. Like in the documentation example. Then just have the target in `target_col`.

**Comment by Vergangenheit** [comment]
Thank you

**Comment by isaacmg** [comment]
Closing this. If you have further questions feel free to re-open.
