### ISSUE TITLE
Link ReadTheDocs in README.md and Getting Started Page

### ISSUE THREAD

**Issue by theadammurphy** [AIStream-Peelout/flow-forecast#356]
1. The README.md does not mention or link to [ReadTheDocs documentation](https://flow-forecast.readthedocs.io/en/latest/). It would be great if it did.

2. The Getting Started [page](https://flow-forecast.atlassian.net/wiki/spaces/FF/pages/92864513/Getting+Started) does mention ReadTheDocs documentation but does not link to it. We should add this [link](https://flow-forecast.readthedocs.io/en/latest/).

**Comment by isaacmg** [comment]
Yes. That could be useful. If you want to make a PR you are welcome to. Otherwise I'll get to it in the future.

**Comment by isaacmg** [comment]
This has now been resolved .
