### ISSUE TITLE
how to use transformer deal with Sequential classification

### ISSUE THREAD

**Issue by mikaizhu** [AIStream-Peelout/flow-forecast#375]
i don't konw how to use transformer to solve sequential classification question. 
In Vallina transformer, there is position embedding, we send it to encoder to extract feature, then  we use this hidden state and sent it to decoder to solve our downstream problem.

my step solution to solve sequential classification are as below:
1. now i have 1D time series, such as 1*128
2. i use pytorch Linear layer nn.Linear(128, 512) to embedding this series and it turns to 1*512
3. then i just use the transformer encoder to learn the feature in it
4. last, i use DNN to classification.

Is there anything else that can be improved in the above steps？thanks?

**Comment by isaacmg** [comment]
This seems to be more of a TS question than a FF specific question. Also classification is not fully supported at the moment.

**Comment by mikaizhu** [comment]
> This seems to be more of a TS question than a FF specific question. Also classification is not fully supported at the moment.

thanks，i find that reshape the time series is good for my job.
