### ISSUE TITLE
Error when using Informer: TypeError: forward() missing 3 required positional arguments: 'x_mark_enc', 'x_dec', and 'x_mark_dec'

### ISSUE THREAD

**Issue by strakehyr** [AIStream-Peelout/flow-forecast#442]
I am trying to use the Informer model and I get to the forward() function error missing 3  arguments. I have gotten here through a regular wandb run, as I was trying to understand what went wrong, and I can't get the full error message when on sweeps.

The df, is a df with the target, several features, and at the end the Time column. Here is part of the code:

```

train_ratio=0.7
valid_ratio=0.15
look_back = 24
horizon=24
n_outputs=1

df = pd.read_csv(file_path)
train_end = round(len(df)*train_ratio)
valid_end = round(len(df)*train_ratio+len(df)*valid_ratio)



wandb_config = {
    "batch_size": 24,
    "lr" : 0.01
}

run = wandb.init(project = 'Transformer test')
  
train_function("PyTorch", {           
      "model_name": "Informer",
      "model_type": "PyTorch",
      "model_params": {
          "n_time_series": len(df.columns)-1,
          "dec_in": len(df.columns)-1,
          "c_out": len(df.columns)-1-n_outputs,
          "seq_len" : look_back,
          "label_len" : 0,
          "out_len" : horizon,
       },
      "dataset_params":
      {  "class": "default",
         "training_path": file_path,
         "validation_path": file_path,
         "test_path": file_path,
         "batch_size":24,
         "forecast_history":look_back,
         "forecast_length":horizon,
         "train_end": int(train_end),
         "target_col": list(df.columns[:n_outputs]),
         "valid_start":int(train_end+1),
         "valid_end": int(valid_end),
         "sort_column": 'Time',
         "num_workers" : 4,
         "pin_memory" : True,
         "relevant_cols": list(df.columns[:-1]),
         "scaler": "StandardScaler", 
         "interpolate": False,
         "feature_param":
          {
            "datetime_params":{
            "hour":"numerical",
            "day":"numerical",
            "month": "numerical",
            "year": "numerical"
            }
          }
      },
      "training_params":
      {
         "criterion":"MSE",
         "optimizer": "SGD",
         "optim_params":
         {
         "lr": 0.01
         },
         "epochs": 10,
         "batch_size":24
      },
      "GCS": False,
      "sweep":False,
      "wandb":{    
          "project": "Transformer test",
          "name": "Some run",
          "tags": "Some tags"},
      "metrics":["MSE"],
      "inference_params": #inference validation done on the test set
      {     
            "forecast_steps": horizon, 
            "datetime_start": dt.datetime.strptime(df['Time'][valid_end][:-6], "%Y-%m-%d %H:%M:%S"),
            "num_prediction_samples": int(len(df)-valid_end),
            "csv_path": file_path,
          #  "decoder_params":{
          #      "decoder_function": "simple_decode", 
          #      "unsqueeze_dim": 1
          #  },
        }
    })
```
   
And here is the full error message: 

  File "<ipython-input-25-dac8ea3f7b3a>", line 63, in <module>
    "csv_path": file_path,

  File "[...]\Python\Python37\site-packages\flood_forecast\trainer.py", line 119, in train_function
    forward_params={}, class2=class2)

  File "[...]\Python\Python37\site-packages\flood_forecast\pytorch_training.py", line 141, in train_transformer_style
    multi_targets=num_targets)

  File "[...]\Python\Python37\site-packages\flood_forecast\pytorch_training.py", line 375, in torch_single_train
    output = model.model(src, **forward_params)

  File "[...]\Python\Python37\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)

TypeError: forward() missing 3 required positional arguments: 'x_mark_enc', 'x_dec', and 'x_mark_dec'

**Comment by strakehyr** [comment]
In case it is needed, here are my library versions:

```
wandb ==0.12.6
torch==1.9.1
flood-forecast==0.984.dev0
```

**Comment by isaacmg** [comment]
The class in dataset parameters needs to be `{ "class": "TemporalLoader,` rather than  "default" anytime you use the Informer model. See here for a full example config https://github.com/AIStream-Peelout/flow-forecast/blob/master/tests/test_informer.json

**Comment by isaacmg** [comment]
Closing if you are still having issues feel free to reopen.

**Comment by strakehyr** [comment]
Now I run into another error. Please, do you have a fully fleshed example or, from the config you linked, the structure of your source file (csv) to know how to prepare the data? This library is extremely untransparent, and all examples seem to have a different version of it. Your example, for instance had a lot of new  arguments I had not seen in the collab or elsewhere. Maybe it will also help others to give it a bit more exposure.
