### ISSUE TITLE
Where is predicted height?

### ISSUE THREAD

**Issue by JJNET** [AIStream-Peelout/flow-forecast#450]
I can't find predicted height.
It looks like DataFrame include inference prediction data like water height and flowrate but I can't find height.
Your Colab sample doesn't show information other than cfs, precipitation, temprerature, preds 
expecially in the last variable df_train_and_test[8:].
https://colab.research.google.com/drive/1IQO2dBaMqZxN5v9HLQvzlvFLM5__VFZP

Task 1 Stream Flow Forecasting of README.md file said this task focuses on forecasting a stream's future **flow/height** (in either cfs or feet respectively) given factors such as current flow, temperature, and precipitation.

**Comment by isaacmg** [comment]
Height is not present for all USGS gages. Therefore only some rivers have height forecasts while all have flow forecasts. Actually probably only 30% or so of the 9k gages have height.
