### ISSUE TITLE
I have a question about LSTM

### ISSUE THREAD

**Issue by twyun24** [AIStream-Peelout/flow-forecast#481]
hi. 
First of all, i'm so grateful to see such an incredible code. Thank you.
But i got some problems.
I took the first to 295th data from "keag_small.csv" and made a new file. 
and started machine running with code <python flood_forecast/trainer.py -p tests/lstm_test.json>
after that, with the function of "infer_now", i got the prediction data from 296~300.
but the result is far away different from the answer in previous file "keag_small".
such as i got prediction 871.921.etc. but the answer in the file "keag_small" was like 234,243,etc.
so i could not find out where the problems were actually happened.
Q1, Does the result is the data of "cfs"?
Q2, if the problem is about lstm, should i use da_rnn?
thank you so much again.

**Comment by isaacmg** [comment]
keag_small is just a very small extract of data to begin with. Training on an even smaller will likely yield poor results. You probably need at least 3k+ rows of temporal data

**Comment by twyun24** [comment]
> keag_small is just a very small extract of data to begin with. Training on an even smaller will likely yield poor results. You probably need at least 3k+ rows of temporal data

thank you so much
