### ISSUE TITLE
I wonder if the result is "cfs"or not

### ISSUE THREAD

**Issue by twyun24** [AIStream-Peelout/flow-forecast#485]
Hello sir.
Thanks for helping me solve the problem 2 days ago. I actually got further understanding of the code.
Anyway, I wish you merry Christmas and have a nice day.

After your consulting, i realized that i still got problems could not figure out by myself.
Here are my questions.
I added the "train_start","test_start" in file "da_rnn.json" cause it seems like missing it.
Then i got 1th to 4000th data from "keag_small.csv" and made a new file named "keag_small_2022.csv"
since there are 4000 data, so i contributed the values like:
"train_start": 1,
"train_end": 2400,
"valid_start":2401,
"valid_end": 3200,
"test_start": 3201,
"test_end": 3995,
to make the percentage of (train : valid : test = 6 :2 :2).
(i blanked the data from 3996 to 4000 since i wanna predict them through machine running).

After that, i used "da_rnn.json" to start machine running with file "keag_small_2022.csv"
naturally it came out a module and i used that module to predicted the data from 3996th~4000th. 
but the result is far away different from the previous values of "cfs". such as results are 66, 67... but the real data of cfs is like 23, 24 ...
So at that time, i wondered if the coming out result is meaning "cfs"or not,
if it's not"cfs", i hope to get your advice to help me go to next step.
For sure, my final goal is to predict the value of "cfs".

i appreciate your last reply and thank you so much again.
Hope you have a nice day.

**Comment by isaacmg** [comment]
Hey sorry for the slow response. Yes if the target_col is cfs then the output of the model will be in cfs.

**Comment by isaacmg** [comment]
Also note that the configuration contained likely do not have the ideal hyperparamters for fitting the model. P

**Comment by twyun24** [comment]
Thank you sir

**Comment by twyun24** [comment]
> Also note that the configuration contained in the files likely do not have the ideal hyperparamters for fitting the model.

Thank you sir.
