### ISSUE TITLE
404 of project board

### ISSUE THREAD

**Issue by chilin0525** [AIStream-Peelout/flow-forecast#592]
Project board link of README.md is not working -> [project board](https://github.com/AIStream-Peeloutt/flow-forecast/projects)

**Comment by isaacmg** [comment]
Yes GitHub change the way projects are structured. The old board can be found at.
https://github.com/AIStream-Peelout/flow-forecast/projects/5

**Comment by chilin0525** [comment]
Got it. Thanks you !
