### ISSUE TITLE
Anyway for specifying "future known" variables?

### ISSUE THREAD

**Issue by pivettamarcos** [AIStream-Peelout/flow-forecast#680]
I've seen that the JSON config file takes in "relevant_cols", but that's just for variables only known prior to the forecast. What if I want to input into the model variables known in the past AND the future? Architectures such as the Temporal Fusion Transformer accept this input logic. Is it possible with Flow Forecast?

Take the following encoder-decoder architecture as an example. Encoder takes past variables and decoder takes encoded past values + future known values.

![image](https://github.com/AIStream-Peelout/flow-forecast/assets/24397077/0ae50e55-7d52-46f6-bb3a-063b0f63a982)

**Comment by isaacmg** [comment]
Any variable in `relevant_columns` that is NOT also in `target_col`  the model will use future values for if the architecture permits (not all of them do).

**Comment by pivettamarcos** [comment]
What if they are not all known in the future?
