### ISSUE TITLE
Model agnostic feature importance

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/flow-forecast#79]
Forecasts require explanation. We want users of flow forecast to be able to easily understand model predictions. We also want to make it easy to explain model decisions to non-technical stakeholders such as epidemiologists, public policy officials, farmers, hydrologists, etc. 

Acceptance criteria 
- [x] Code merged into master 
- [ ] General feature importance plots to work with any model. (Current implementation cannot work with transformer)
- [x] Parameter to log feature plots to Wandb
- [x] Successfully passing unit tests including flow train test.
- [x] Replace NamedArray with pytorch NamedTensor.
- [x] Update plot configuration to display heatmap for each feature better.

**Comment by MaggieWYZW** [comment]
Further fixes on the figures.
